/**
 * generated by Xtext 2.10.0
 */
package edu.kit.ipd.sdq.kamp.ruledsl.validation;

import edu.kit.ipd.sdq.kamp.ruledsl.validation.AbstractKampRuleLanguageValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class KampRuleLanguageValidator extends AbstractKampRuleLanguageValidator {
}
