/*
 * generated by Xtext 2.11.0
 */
package edu.kit.ipd.sdq.kamp.ruledsl.scoping;

import tools.vitruv.dsls.mirbase.scoping.MirBaseScopeProvider;

public abstract class AbstractKampRuleLanguageScopeProvider extends MirBaseScopeProvider {
}
