/**
 * generated by Xtext 2.10.0
 */
package edu.kit.ipd.sdq.kamp.ruledsl.ui.quickfix;

import tools.vitruv.dsls.mirbase.ui.quickfix.MirBaseQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class KampRuleLanguageQuickfixProvider extends MirBaseQuickfixProvider {
}
