/*
 * generated by Xtext 2.11.0
 */
package edu.kit.ipd.sdq.kamp.ruledsl.parser.antlr;

import com.google.inject.Inject;
import edu.kit.ipd.sdq.kamp.ruledsl.parser.antlr.internal.InternalKampRuleLanguageParser;
import edu.kit.ipd.sdq.kamp.ruledsl.services.KampRuleLanguageGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class KampRuleLanguageParser extends AbstractAntlrParser {

	@Inject
	private KampRuleLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalKampRuleLanguageParser createParser(XtextTokenStream stream) {
		return new InternalKampRuleLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RuleFile";
	}

	public KampRuleLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KampRuleLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
