/**
 * generated by Xtext 2.11.0
 */
package edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl;

import edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.ForwardEReference;
import edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.KampRuleLanguagePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Forward EReference</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ForwardEReferenceImpl extends PropagationReferenceImpl implements ForwardEReference
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ForwardEReferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return KampRuleLanguagePackage.Literals.FORWARD_EREFERENCE;
  }

} //ForwardEReferenceImpl
