/**
 * generated by Xtext 2.10.0
 */
package edu.kit.ipd.sdq.kamp.ruledsl;

import edu.kit.ipd.sdq.kamp.ruledsl.KampRuleLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class KampRuleLanguageStandaloneSetup extends KampRuleLanguageStandaloneSetupGenerated {
  public static void doSetup() {
    new KampRuleLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
