/*
 * generated by Xtext 2.10.0
 */
package edu.kit.ipd.sdq.kamp.ruledsl

import com.google.inject.Inject

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class KampRuleLanguageStandaloneSetup extends KampRuleLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new KampRuleLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
