/**
 * generated by Xtext 2.10.0
 */
package edu.kit.ipd.sdq.kamp.ruledsl.ui;

import edu.kit.ipd.sdq.kamp.ruledsl.ui.AbstractKampRuleLanguageUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class KampRuleLanguageUiModule extends AbstractKampRuleLanguageUiModule {
  public KampRuleLanguageUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
