/**
 * generated by Xtext 2.11.0
 */
package edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage;

import tools.vitruv.dsls.mirbase.mirBase.MetaclassReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Backward EReference</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.KampRuleLanguagePackage#getBackwardEReference()
 * @model
 * @generated
 */
public interface BackwardEReference extends PropagationReference, MetaclassReference
{
} // BackwardEReference
