/**
 * generated by Xtext 2.11.0
 */
package edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Forward EReference</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.KampRuleLanguagePackage#getForwardEReference()
 * @model
 * @generated
 */
public interface ForwardEReference extends PropagationReference
{
} // ForwardEReference
