/**
 * generated by Xtext 2.11.0
 */
package edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import tools.vitruv.dsls.mirbase.mirBase.MirBasePackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.KampRuleLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface KampRuleLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "kampRuleLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.kit.edu/ipd/sdq/kamp/ruledsl/KampRuleLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "kampRuleLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  KampRuleLanguagePackage eINSTANCE = edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.RuleFileImpl <em>Rule File</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.RuleFileImpl
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleLanguagePackageImpl#getRuleFile()
   * @generated
   */
  int RULE_FILE = 0;

  /**
   * The feature id for the '<em><b>Metamodel Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FILE__METAMODEL_IMPORTS = MirBasePackage.MIR_BASE_FILE__METAMODEL_IMPORTS;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FILE__NAME = MirBasePackage.MIR_BASE_FILE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FILE__RULES = MirBasePackage.MIR_BASE_FILE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Rule File</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FILE_FEATURE_COUNT = MirBasePackage.MIR_BASE_FILE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleImpl <em>Kamp Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleImpl
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleLanguagePackageImpl#getKampRule()
   * @generated
   */
  int KAMP_RULE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KAMP_RULE__NAME = 0;

  /**
   * The feature id for the '<em><b>Source</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KAMP_RULE__SOURCE = 1;

  /**
   * The feature id for the '<em><b>Lookups</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KAMP_RULE__LOOKUPS = 2;

  /**
   * The number of structural features of the '<em>Kamp Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KAMP_RULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.LookupImpl <em>Lookup</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.LookupImpl
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleLanguagePackageImpl#getLookup()
   * @generated
   */
  int LOOKUP = 2;

  /**
   * The number of structural features of the '<em>Lookup</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOKUP_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.PropagationReferenceImpl <em>Propagation Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.PropagationReferenceImpl
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleLanguagePackageImpl#getPropagationReference()
   * @generated
   */
  int PROPAGATION_REFERENCE = 3;

  /**
   * The feature id for the '<em><b>Feature</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPAGATION_REFERENCE__FEATURE = LOOKUP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Propagation Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPAGATION_REFERENCE_FEATURE_COUNT = LOOKUP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.ForwardEReferenceImpl <em>Forward EReference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.ForwardEReferenceImpl
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleLanguagePackageImpl#getForwardEReference()
   * @generated
   */
  int FORWARD_EREFERENCE = 4;

  /**
   * The feature id for the '<em><b>Feature</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORWARD_EREFERENCE__FEATURE = PROPAGATION_REFERENCE__FEATURE;

  /**
   * The number of structural features of the '<em>Forward EReference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORWARD_EREFERENCE_FEATURE_COUNT = PROPAGATION_REFERENCE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.BackwardEReferenceImpl <em>Backward EReference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.BackwardEReferenceImpl
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleLanguagePackageImpl#getBackwardEReference()
   * @generated
   */
  int BACKWARD_EREFERENCE = 5;

  /**
   * The feature id for the '<em><b>Feature</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKWARD_EREFERENCE__FEATURE = PROPAGATION_REFERENCE__FEATURE;

  /**
   * The feature id for the '<em><b>Metamodel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKWARD_EREFERENCE__METAMODEL = PROPAGATION_REFERENCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Metaclass</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKWARD_EREFERENCE__METACLASS = PROPAGATION_REFERENCE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Backward EReference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKWARD_EREFERENCE_FEATURE_COUNT = PROPAGATION_REFERENCE_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.RuleFile <em>Rule File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule File</em>'.
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.RuleFile
   * @generated
   */
  EClass getRuleFile();

  /**
   * Returns the meta object for the attribute '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.RuleFile#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.RuleFile#getName()
   * @see #getRuleFile()
   * @generated
   */
  EAttribute getRuleFile_Name();

  /**
   * Returns the meta object for the containment reference list '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.RuleFile#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.RuleFile#getRules()
   * @see #getRuleFile()
   * @generated
   */
  EReference getRuleFile_Rules();

  /**
   * Returns the meta object for class '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.KampRule <em>Kamp Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Kamp Rule</em>'.
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.KampRule
   * @generated
   */
  EClass getKampRule();

  /**
   * Returns the meta object for the attribute '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.KampRule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.KampRule#getName()
   * @see #getKampRule()
   * @generated
   */
  EAttribute getKampRule_Name();

  /**
   * Returns the meta object for the containment reference '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.KampRule#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Source</em>'.
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.KampRule#getSource()
   * @see #getKampRule()
   * @generated
   */
  EReference getKampRule_Source();

  /**
   * Returns the meta object for the containment reference list '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.KampRule#getLookups <em>Lookups</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lookups</em>'.
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.KampRule#getLookups()
   * @see #getKampRule()
   * @generated
   */
  EReference getKampRule_Lookups();

  /**
   * Returns the meta object for class '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.Lookup <em>Lookup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lookup</em>'.
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.Lookup
   * @generated
   */
  EClass getLookup();

  /**
   * Returns the meta object for class '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.PropagationReference <em>Propagation Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Propagation Reference</em>'.
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.PropagationReference
   * @generated
   */
  EClass getPropagationReference();

  /**
   * Returns the meta object for the reference '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.PropagationReference#getFeature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Feature</em>'.
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.PropagationReference#getFeature()
   * @see #getPropagationReference()
   * @generated
   */
  EReference getPropagationReference_Feature();

  /**
   * Returns the meta object for class '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.ForwardEReference <em>Forward EReference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Forward EReference</em>'.
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.ForwardEReference
   * @generated
   */
  EClass getForwardEReference();

  /**
   * Returns the meta object for class '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.BackwardEReference <em>Backward EReference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Backward EReference</em>'.
   * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.BackwardEReference
   * @generated
   */
  EClass getBackwardEReference();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  KampRuleLanguageFactory getKampRuleLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.RuleFileImpl <em>Rule File</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.RuleFileImpl
     * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleLanguagePackageImpl#getRuleFile()
     * @generated
     */
    EClass RULE_FILE = eINSTANCE.getRuleFile();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE_FILE__NAME = eINSTANCE.getRuleFile_Name();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE_FILE__RULES = eINSTANCE.getRuleFile_Rules();

    /**
     * The meta object literal for the '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleImpl <em>Kamp Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleImpl
     * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleLanguagePackageImpl#getKampRule()
     * @generated
     */
    EClass KAMP_RULE = eINSTANCE.getKampRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute KAMP_RULE__NAME = eINSTANCE.getKampRule_Name();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KAMP_RULE__SOURCE = eINSTANCE.getKampRule_Source();

    /**
     * The meta object literal for the '<em><b>Lookups</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KAMP_RULE__LOOKUPS = eINSTANCE.getKampRule_Lookups();

    /**
     * The meta object literal for the '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.LookupImpl <em>Lookup</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.LookupImpl
     * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleLanguagePackageImpl#getLookup()
     * @generated
     */
    EClass LOOKUP = eINSTANCE.getLookup();

    /**
     * The meta object literal for the '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.PropagationReferenceImpl <em>Propagation Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.PropagationReferenceImpl
     * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleLanguagePackageImpl#getPropagationReference()
     * @generated
     */
    EClass PROPAGATION_REFERENCE = eINSTANCE.getPropagationReference();

    /**
     * The meta object literal for the '<em><b>Feature</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPAGATION_REFERENCE__FEATURE = eINSTANCE.getPropagationReference_Feature();

    /**
     * The meta object literal for the '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.ForwardEReferenceImpl <em>Forward EReference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.ForwardEReferenceImpl
     * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleLanguagePackageImpl#getForwardEReference()
     * @generated
     */
    EClass FORWARD_EREFERENCE = eINSTANCE.getForwardEReference();

    /**
     * The meta object literal for the '{@link edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.BackwardEReferenceImpl <em>Backward EReference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.BackwardEReferenceImpl
     * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleLanguagePackageImpl#getBackwardEReference()
     * @generated
     */
    EClass BACKWARD_EREFERENCE = eINSTANCE.getBackwardEReference();

  }

} //KampRuleLanguagePackage
