/**
 * generated by Xtext 2.11.0
 */
package edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.KampRuleLanguagePackage
 * @generated
 */
public interface KampRuleLanguageFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  KampRuleLanguageFactory eINSTANCE = edu.kit.ipd.sdq.kamp.ruledsl.kampRuleLanguage.impl.KampRuleLanguageFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Rule File</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule File</em>'.
   * @generated
   */
  RuleFile createRuleFile();

  /**
   * Returns a new object of class '<em>Kamp Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Kamp Rule</em>'.
   * @generated
   */
  KampRule createKampRule();

  /**
   * Returns a new object of class '<em>Lookup</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lookup</em>'.
   * @generated
   */
  Lookup createLookup();

  /**
   * Returns a new object of class '<em>Propagation Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Propagation Reference</em>'.
   * @generated
   */
  PropagationReference createPropagationReference();

  /**
   * Returns a new object of class '<em>Forward EReference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Forward EReference</em>'.
   * @generated
   */
  ForwardEReference createForwardEReference();

  /**
   * Returns a new object of class '<em>Backward EReference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Backward EReference</em>'.
   * @generated
   */
  BackwardEReference createBackwardEReference();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  KampRuleLanguagePackage getKampRuleLanguagePackage();

} //KampRuleLanguageFactory
