/**
 * generated by Xtext 2.11.0
 */
package edu.kit.ipd.sdq.kamp.ruledsl.ide;

import edu.kit.ipd.sdq.kamp.ruledsl.ide.AbstractKampRuleLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class KampRuleLanguageIdeModule extends AbstractKampRuleLanguageIdeModule {
}
