/*
 * generated by Xtext 2.11.0
 */
package edu.kit.ipd.sdq.kamp.ruledsl.ui.tests;

import com.google.inject.Injector;
import edu.kit.ipd.sdq.kamp.ruledsl.ui.internal.RuledslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class KampRuleLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RuledslActivator.getInstance().getInjector("edu.kit.ipd.sdq.kamp.ruledsl.KampRuleLanguage");
	}

}
