/**
 * generated by Xtext 2.10.0
 */
package edu.kit.ipd.sdq.kamp.ruledsl.ui.contentassist;

import edu.kit.ipd.sdq.kamp.ruledsl.ui.contentassist.AbstractKampRuleLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class KampRuleLanguageProposalProvider extends AbstractKampRuleLanguageProposalProvider {
}
